compile:
	npx hardhat compile

deploy-testnet:
	npx hardhat run scripts/deploy.ts --network baseSepolia

interact:
	npx hardhat run scripts/interact.ts --network baseSepolia

clean:
	npx hardhat clean
	rm -rf typechain-types
